#ifndef CONSTANTS_H
#define CONSTANTS_H

#define PROGRAM_NAME "nothydrus"
#define INIT_DIRECTORY "."PROGRAM_NAME
#define MAIN_DATABASE_NAME "main.db"

#define DEFAULT_DIRECTORY_MODE S_IRWXU|S_IRWXG|S_IROTH|S_IXOTH

#endif
