#ifndef CONSTANTS_H
#define CONSTANTS_H

#define PROGRAM_NAME "nothydrus"
#define INIT_DIRECTORY "."PROGRAM_NAME
#define MAIN_DATABASE_NAME "main.db"

#define DEFAULT_DIRECTORY_MODE S_IRWXU|S_IRWXG|S_IROTH|S_IXOTH

#define SEARCH_MAX_SQL_LEN 2000

//filetypes
#define FILETYPE_NONE 0
#define FILETYPE_OTHER 1
#define FILETYPE_IMAGE 2
#define FILETYPE_VIDEO 3

#endif
